INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE,IMAG ) VALUES (0, 'Restaurant1', 'Spectialité poulet', 10.0, 10.0, 10.0, 10.0,'0.jpg');

INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE,IMAG) VALUES (1,  'Restaurant2', 'Spectialité patte', 10.0, 10.0, 10.0, 10.0,'1.jpg');

INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE,IMAG ) VALUES (2, 'Restaurant2', 'Spectialité Brochette', 10.0, 10.0, 10.0, 10.0,'2.jpg');

INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE,IMAG) VALUES (3, 'Restaurant3', 'Spectialité Parisien', 10.0, 10.0, 10.0, 10.0,'3.jpg');

INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE,IMAG ) VALUES (4, 'Restaurant4', 'Spectialité Chinois', 10.0, 10.0, 10.0, 10.0,'4.jpg');

INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE,IMAG ) VALUES (5, 'Restaurant5', 'Spectialité pizza', 10.0, 10.0, 10.0, 10.0,'5.jpg');

INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE ,IMAG) VALUES (6, 'Restaurant6', 'Spectialité riz', 10.0, 10.0, 10.0, 10.0,'6.jpg');

INSERT INTO RESTAURANT (ID, NOM,DESCRIPTION , MOYEN,QNOURITURE , QSALLE, QSERVICE,IMAG ) VALUES (7 , 'Restaurant7', 'Spectialité mechou', 5.0, 5.0, 5.0, 5.0,'7.jpg');